server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/reserve
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123