server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/reserve
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


custom:
  cookieDomain: localhost
  jwt:
    secretKey: c81cc9e3bd85b4efa605703f92eb7148fe5394fa68c0fea13834ab5f2ab2adeac6af25b9f07306dec810969176d6d03a538f00c6556fadb6ab212be25c68ca55
    access-token-validity-in-milliseconds: 10800000
    refresh-token-validity-in-milliseconds: 1209600000

logging:
  level:
    org.springframework.*: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

    # for native query
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    sql: debug
